export const id = {
    pembina: [
      {
        id: 1,
        title: "Dr.Eng Danu Dwi Sanjoyo, ST., MT.",
        image: "/image/kosong.png",
        codedosen: "DWJ",
        nip: "14880082",
        posisi: "Pembina Utama",
      },
      {
        id: 2,
        title: "Sri Astuti, S.T., M.T.",
        image: "/image/kosong.png",
        codedosen: "TUI",
        nip: "20850004",
        posisi: "Pembina",
      },
      {
        id: 3,
        title: "Sussi, S.Si., MT.",
        image: "/image/kosong.png",
        codedosen: "SUI",
        nip: "20830010",
        posisi: "Pembina",
      },
      {
        id: 4,
        title: "Bagus Aditya, S.T., M.T",
        image: "/image/kosong.png",
        codedosen: "BGY",
        nip: "20900007",
        posisi: "Pembina",
      },
      {
        id: 4,
        title: "Dr.Eng. Favian Dewanta, S.T., M.Eng.",
        image: "/image/kosong.png",
        codedosen: "FAV",
        nip: "15870022",
        posisi: "Pembina",
      },
  
    ],
    struktur: [
      {
        id: 1,
        title: "Adam Hadi Pratama",
        desc: "Koordinator Asisten",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 2,
        title: "Muhammad Rafi Ediananta",
        desc: "Wakil Koordinator Asisten",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 3,
        title: "Retno Fauziah Istiqomah",
        desc: "Koordinator Riset",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 4,
        title: "Fadilah Putri Sukoco",
        desc: "Bendahara",
        image: "/image/kosong.png",
        divisi: "Geographical Information System",
      },
      {
        id: 5,
        title: "Satria Winekas Herlambang",
        desc: "Sekretaris",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 6,
        title: "Dias Daffa Wiwaha",
        desc: "Kepala HRD",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 7,
        title: "Moch Firza Yudistira Meizia",
        desc: "Kepala Media",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 8,
        title: "Muhammad Priambodo Satrio Wibowo",
        desc: "Kepala Logistik",
        image: "/image/kosong.png",
        divisi: "Geographical Information System",
      },

    ],
  
    bd: [
      {
        id: 1,
        title: "Zaidan Muhammad Mahdi",
        desc: "Kepala Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 2,
        title: "Devan Ramadhana",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 3,
        title: "Dias Daffa Wiwaha",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 4,
        title: "Alfarelzi",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 5,
        title: "Rr Meidita Thifal Lelyta",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 6,
        title: "Agni Pulung Tondo Drawino",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      {
        id: 7,
        title: "Rafi Andhika Putra Pratama",
        desc: "Anggota Divisi",
        image: "/image/kosong.png",
        divisi: "Big Data",
      },
      
    ],
    cs: [
      {
        id: 1,
        title: "Ahda Akmalul Ilmi",
        desc: "Kepala Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 2,
        title: "Hubert Igor",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 3,
        title: "M. Reza Manazil Al Qomar",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 4,
        title: "Rayhan Dhafi",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 5,
        title: "Hubert Igor",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 6,
        title: "Thufail Agung Fathi",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 7,
        title: "M. Surya Danendra Pabana",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 8,
        title: "Muhammad Reza Aditria",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 9,
        title: "Pandu Dwi Nugraha Surya Putra",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      
    ],
    gt: [
      {
        id: 1,
        title: "Fabiano Abbey Karo Sekali",
        desc: "Kepala Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 2,
        title: "Fellica Clara Cindy",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 3,
        title: "Geva Almer Hariri",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 4,
        title: "Moch Firza Yudistira Meizia",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 5,
        title: "Raehan Abdillah",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 6,
        title: "Putra Pratama Sijabat",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 7,
        title: "Fayyadh Asady",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 8,
        title: "Rizki Ananda",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 9,
        title: "Nathanael Dwi Cahyo",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      {
        id: 10,
        title: "Mohamad Farrel William Rosyadi",
        desc: "Anggota Divisi ",
        image: "/image/kosong.png",
        divisi: "Game Tech",
      },
      
    ],
    gis: [
      {
        id: 1,
        title: "Abdurrasyid Malvin Nugraha",
        desc: "Kepala Divisi ",
        image: "/image/kosong.png",
        divisi: "Cyber Security",
      },
      {
        id: 2,
        title: "M. Priambodo Satrio Wibowo",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 3,
        title: "Divany Maulidyna Putri",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 4,
        title: "Fadilah Putri Sukoco",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 5,
        title: "Yulintyandra Puja Antanita",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 6,
        title: "Firscha Aulia Ghassani Fikri",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 7,
        title: "Muhammad Abdul Hakim",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      {
        id: 8,
        title: "Muhammad Abyan Harits",
        desc: "Anggota Divisi  ",
        image: "/image/kosong.png",
        divisi: "Geographic Information System",
      },
      
    ],
  };
  